using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GuessTheNumber
{
    class Program
    {
        static void Main(string[] args)
        {
            // The code provided will print ‘Hello World’ to the console.
            // Press Ctrl+F5 (or go to Debug > Start Without Debugging) to run your app.
            Console.WriteLine("Guess the Number");
            Console.WriteLine("By Zak Mitchell");
            Console.WriteLine("");
            Console.WriteLine("Try to guess a random number generated by the computer!");

            Random rand = new Random();
            int secretNumber = rand.Next(1,10);
            Console.WriteLine("Our secret number is " + secretNumber);

            Console.WriteLine("Enter a number guess between 1 and 9");
            int guess = Convert.ToInt32(Console.ReadLine());
            int guessNum = 1;
            Console.WriteLine("You guessed " + guess);

            while (guess != secretNumber)
            {
                //keep guessing
                
                Console.WriteLine("Wrong! Try again!");

                if (secretNumber < guess)
                {
                    Console.WriteLine("The secret number is less than " + guess);
                }
                else
                {
                    Console.WriteLine("The secret number is bigger than " + guess);
                }
                //read a new guess
                Console.WriteLine("Guess another number");
                guess = Convert.ToInt32(Console.ReadLine());
                guessNum +=1;

            }
            //now the correct number has been guessed
            Console.WriteLine("You guessed the correct number!!");
            Console.WriteLine("You guessed " + guessNum + " time(s)");

            Console.ReadKey();

            // Go to http://aka.ms/dotnet-get-started-console to continue learning how to build a console app! 
        }
    }
}
