using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GuessTheNumber
{
    class Program
    {
        static void Main(string[] args)
        {
            // The code provided will print ‘Hello World’ to the console.
            // Press Ctrl+F5 (or go to Debug > Start Without Debugging) to run your app.
            Console.WriteLine("Guess the Number");
            Console.WriteLine("By Zak Mitchell");
            Console.WriteLine("");
            Console.WriteLine("Try to guess a random number generated by the computer!");

            bool keepPlaying = true;
            while (keepPlaying == true)
            {



                Console.WriteLine("Generating secret number ... GENERATED!");

                Random rand = new Random();
                int secretNumber = rand.Next(1, 21);
                int guess = 0;
                Console.WriteLine("Our secret number is " + secretNumber);
                while(guess < 1 || guess > 20)
                {
                    Console.WriteLine("Enter a number guess between 1 and 20");
                    guess = Convert.ToInt32(Console.ReadLine());
                }
                int guessNum = 1;


                while (guess != secretNumber || guessNum ==5)
                {
                    //keep guessing

                    Console.WriteLine("Wrong! Try again!");

                    if (secretNumber < guess)
                    {
                        Console.WriteLine("The secret number is less than " + guess);
                    }
                    else
                    {
                        Console.WriteLine("The secret number is bigger than " + guess);
                    }
                    //read a new guess
                    Console.WriteLine("Guess another number between 1 and 20");
                    guess = Convert.ToInt32(Console.ReadLine());
                    while(guess <1 || guess>20)
                    {
                        Console.WriteLine("Guess another number between 1 and 20");
                        guess = Convert.ToInt32(Console.ReadLine());
                    }
                    ++guessNum; // this adds 1 to the number

                }
                //now the correct number has been guessed
                if (guessNum < 5)
                {
                    Console.WriteLine("You guessed the correct number!!");
                    Console.WriteLine("You guessed " + guessNum + " time(s)");
                }
                else
                {
                    Console.WriteLine("You guessed too much! You Suck!!");
                }
                // ask if they want to play again
                Console.WriteLine("Play again? (y/n)");
                Console.WriteLine("");
                string resartResponce = Console.ReadLine();
                if (resartResponce == "y")
                {
                    //Resart
                    keepPlaying = true;
                }
                else
                {
                    //exit
                    keepPlaying = false;
                }

            }//end of while loop

            // Go to http://aka.ms/dotnet-get-started-console to continue learning how to build a console app! 
        }
    }
}
